services:
  - type: web
    name: appointment-predictor
    env: python
    buildCommand: pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd backend && gunicorn core.wsgi:application
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
